# name: 'Chromatic'

# on:
#   push:
#     branches:
#       - main
#     paths:
#        - "!scripts/**"

#   # "You must append a colon (:) to all events, including events without configuration."
#   # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-multiple-events-with-activity-types-or-configuration
#   pull_request:
#     paths: # Only run if the frontend has changed
#       - 'packages/components/**'
#       - '.storybook/**'
#       - 'package.json'
#       - "!scripts/**"

# permissions:
#    contents: write
   
# concurrency:
#     group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#     # Allow snapshot updates to finish, so that we don't need to wait for Storybook to build again
#     cancel-in-progress: false

# jobs:
#   chromatic-deployment:
#     runs-on: ubuntu-latest
#     outputs:
#       storybook-url: ${{ steps.publish.outputs.storybookUrl }}
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 # 👈 Required to retrieve git history (https://www.chromatic.com/docs/github-actions)


#       - uses: pnpm/action-setup@v2
#       - run: corepack enable

#       - uses: actions/setup-node@v3
#         with:
#           node-version: "18"
#           cache: pnpm

#       - name: Install dependencies
#         run: pnpm install

#       - name: Build Packages
#         run: pnpm run build

#       - name: Build Storybook
#         run: pnpm run build:storybook

#       - name: Publish to Chromatic
#         uses: chromaui/action@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           projectToken: a6e45b3693a3
#           buildScriptName: build:storybook
#           exitOnceUploaded: true
#           exitZeroOnChanges: true