packages:
  - playground/*
  - packages/*
  - packages/*/*
  - .docs
catalog:
  '@antfu/eslint-config': ^4.3.0
  '@babel/traverse': ^7.25.9
  '@clack/prompts': ^0.10.0
  '@egoist/tailwindcss-icons': ^1.9.0
  '@floating-ui/dom': ^1.6.13
  '@floating-ui/utils': ^0.2.9
  '@floating-ui/vue': ^1.1.6
  '@iconify-json/ph': ^1.2.2
  '@iconify/vue': ^4.1.2
  '@nuxt/kit': ^3.15.4
  '@nuxt/schema': ^3.15.4
  '@oku-ui/motion': ^0.4.1
  '@radix-ui/colors': ^3.0.0
  '@shikijs/vitepress-twoslash': ^1.22.2
  '@stackblitz/sdk': ^1.11.0
  '@storybook/addon-essentials': ^8.5.8
  '@storybook/addon-interactions': ^8.5.8
  '@storybook/addon-links': ^8.5.8
  '@storybook/blocks': ^8.5.8
  '@storybook/testing-library': ^0.2.2
  '@storybook/vue3': ^8.5.8
  '@storybook/vue3-vite': ^8.5.8
  '@testing-library/vue': ^8.1.0
  '@tsconfig/node20': ^20.1.4
  '@types/babel__traverse': ^7.20.6
  '@types/jsdom': ^21.1.7
  '@types/markdown-it': ^14.1.2
  '@types/node': ^22.13.5
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vitest/coverage-v8': ^3.0.6
  '@vue/test-utils': ^2.4.6
  aria-hidden: ^1.2.4
  autoprefixer: ^10.4.20
  bumpp: ^10.0.3
  changelogen: ^0.5.7
  chokidar: ^4.0.3
  chromatic: ^11.25.2
  codesandbox: ^2.2.3
  eslint: ^9.21.0
  eslint-plugin-storybook: ^0.11.3
  esno: ^4.8.0
  fast-glob: ^3.3.2
  filter-anything: ^4.0.3
  globby: ^14.1.0
  happy-dom: ^17.1.2
  jiti: ^2.4.2
  jsdom: ^26.0.0
  lint-staged: ^15.4.3
  markdown-it: ^14.1.0
  npm-run-all2: ^7.0.2
  nuxt: ^3.15.4
  nx: ^20.4.6
  ofetch: ^1.4.1
  pathe: ^2.0.3
  react: ^19.0.0
  react-dom: ^19.0.0
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  storybook: ^8.5.8
  storybook-dark-mode: ^4.0.2
  tsup: ^8.3.6
  turbo: ^2.3.7
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unplugin-vue-components: ^28.4.0
  vite: ^6.1.1
  vite-plugin-dts: ^4.5.0
  vite-plugin-externalize-deps: ^0.9.0
  vite-plugin-pages: ^0.32.5
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^1.5.0
  vitest: ^3.0.6
  vitest-axe: 1.0.0-pre.5
  vitest-canvas-mock: ^0.3.3
  vue-router: ^4.5.0
  vue-sonner: ^1.2.5
  vue-tsc: ^2.2.2
