// NAMES
export const SCROLL_AREA_NAME = 'OkuScrollArea'
export const SCROLL_AREA_VIEWPORT = 'OkuScrollAreaViewport'
export const SCROLL_AREA_THUMB_NAME = 'OkuScrollAreaThumb'
export const SCROLL_AREA_SCROLLBAR_NAME = 'OkuScrollAreaScrollbar'
export const SCROLL_AREA_SCROLLBAR_HOVER = 'OkuScrollAreaScrollbarHover'
export const SCROLL_AREA_THUMB_IMPL_NAME = 'OkuScrollAreaThumbImpl'
export const SCROLL_AREA_SCROLLBAR_IMPL_NAME = 'OkuScrollAreaScrollbarImpl'
export const SCROLL_AREA_SCROLLBAR_SCROLL_NAME = 'OkuScrollAreaScrollbarScroll'
export const SCROLL_AREA_SCROLLBAR_VISIBLE_NAME = 'OkuScrollAreaScrollbarVisible'
export const SCROLL_AREA_SCROLLBAR_AUTO_NAME = 'OkuScrollAreaScrollbarAuto'
export const SCROLL_AREA_CORNER_NAME = 'OkuScrollAreaCorner'
export const SCROLL_AREA_CORNER_IMPL_NAME = 'OkuScrollAreaCornerImpl'
export const SCROLL_AREA_SCROLLBAR_X = 'OkuScrollAreaScrollbarX'
export const SCROLL_AREA_SCROLLBAR_Y = 'OkuScrollAreaScrollbarY'
