export { default as ScrollArea } from './ScrollArea.vue'
export { default as ScrollAreaViewport } from './ScrollAreaViewport.vue'
export { default as ScrollAreaContent } from './ScrollAreaContent.vue'
export { default as ScrollAreaScrollbar } from './ScrollAreaScrollbar.vue'
export { default as ScrollAreaCorner } from './ScrollAreaCorner.vue'
export { default as ScrollAreaThumb } from './ScrollAreaThumb.vue'
